#!/bin/bash

vagrant up
vagrant demo use reporting,wordpress
vagrant snapshot back master
vagrant snapshot back wordpress
vagrant provision --provision-with shell,host
vagrant ssh master    -c 'sudo service pe-puppetserver start' #WTF
vagrant ssh master    -c 'sudo puppet agent -t'
vagrant ssh wordpress -c 'sudo puppet agent -t'
vagrant ssh master    -c 'sudo puppet agent --disable'
vagrant ssh wordpress -c 'sudo puppet agent --disable'
