forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-vcsrepo'
mod 'node_manager',
  :git => 'https://github.com/ccaum/prosvcs-node_manager.git',
  :ref => 'e8595d6f29fc8d4e042ffcf4dea1a24983ab95e2'
mod 'puppetlabs/pe_gem'
